name: ci
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  nim:
    strategy:
      matrix:
        fuzzer:
          - ci1
          - ci2
        img:
          - latest
      fail-fast: false
    name: ${{ matrix.fuzzer }}@${{ matrix.img }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      options: --privileged
    steps:
    - uses: actions/checkout@v1
    - name: fuzz_${{ matrix.fuzzer }}
      run: |
        #apk add --no-cache afl util-linux
        apt update && apt install -y iputils-ping
        sysctl -w kernel.core_pattern=core
        sysctl -w kernel.sched_child_runs_first=1
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
        ping google.ca > /tmp/ping.out &
        sleep 60 # sleep here works
#    - if: github.base_ref == 'refs/heads/master'
#      name: wait 4 hours for master
#      run: sleep 16400
    - run: echo hi
    - name: wait half hour
      run: sleep 60
    - name: close fuzzer
      run: cat /tmp/ping.out
      #    - name: list hangs (below 16k)
      #      run: find tests/fuzzer/out-${{ matrix.fuzzer}}/hangs -type f -size -16384c -exec echo {} \; -exec curl -F data=@\"{}\" https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
      #    - name: list hangs (16k & above)
      #      run: find tests/fuzzer/out-${{ matrix.fuzzer}}/hangs -type f -size +16383c -exec echo {} \; -exec curl -F data=@\"{}\" https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
      #    - name: list crashes
      #      run: find tests/fuzzer/out-${{ matrix.fuzzer }}/crashes -type f -exec echo {} \; -exec curl -F data=@\"{}\" https://ipfs.infura.io:5001/api/v0/add \; -exec xxd {} \;
      #      ## Hangs won't be counted against the status, as a KDF is meant to be slow...
      #    - name: fuzzer status
      #      run: |
      #        ! ls -1A tests/fuzzer/out-${{ matrix.fuzzer }}/crashes | grep -q .
